name: Tiredful

on:
  push:
    branches:                                
      - main

jobs:
  sast-snyk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v4
        with:
          node-version: '14' 

      # Install dependencies 
      - name: Install dependencies
        run: npm install express

      - name: Run Snyk
        run: snyk code test --json-file-output=snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Snyk
          path: snyk-results.json
        if: always()

  build:
    runs-on: ubuntu-22.04
    needs: sast-snyk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t natalieaoya/simple-node-app:latest .
          docker push natalieaoya/simple-node-app:latest

  image-scan:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        uses: snyk/actions/setup@master


      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' 

      - name: Install Node modules
        run: npm install express

      - name: Run Snyk
        run: snyk test --docker natalieaoya/simple-node-app:latest --json-file-output=image-scan.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true    

      - uses: actions/upload-artifact@v4
        with:
          name: Image Scan
          path: image-scan.json
        if: always()


  deploy:
    runs-on: ubuntu-22.04
    needs: image-scan
    steps:
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Isolate envoronments
        run: |
          kubectl create namespace prod
          kubectl create namespace dev
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f rbac.yaml
          kubectl apply -f service-account.yaml
          kubectl apply -f network-policies.yaml
          kubectl config set-context --current --namespace=prod
          kubectl apply -f prod-deployment.yaml
          kubectl apply -f service.yaml

